openapi: 3.0.0
info:
  title: Simulation Data Interface
  description: API interface for controlling simulation lifecycle, configuration, and event propagation.
  version: 1.1.0
tags:
  - name: Initial Setting
    description: 1.x Simulation Initialization & Configuration
  - name: Execution
    description: 2.x Simulation Runtime Control
  - name: Event Propagation
    description: 3.x Dynamic Event Handling & Monitoring

paths:
  # ==========================================
  # 1. Simulation Initial Setting
  # ==========================================
  /sim/init:
    $ref: './paths/1.1.1.yaml#/sim/init'
  /sim/executor/vdt:
    $ref: './paths/1.1.2.yaml#/sim/executor/vdt'
  /sim/executor/uatm:
    $ref: './paths/1.1.2.yaml#/sim/executor/uatm'
  /sim/executor/vpos:
    $ref: './paths/1.1.2.yaml#/sim/executor/vpos'
  /config/ip/uatm:
    $ref: './paths/1.1.3.yaml#/config/ip/uatm'
  /config/ip/vpos:
    $ref: './paths/1.1.3.yaml#/config/ip/vpos'
  /config/ip/vehicles:
    $ref: './paths/1.1.3.yaml#/config/ip/vehicles'
  /config/ip/access:
    $ref: './paths/1.1.4.yaml#/config/ip/access'
  /config/vehicle:
    $ref: './paths/1.2.1.yaml#/config/vehicle'
  /config/corridor:
    $ref: './paths/1.2.1.yaml#/config/corridor'
  /config/vertiport:
    $ref: './paths/1.2.1.yaml#/config/vertiport'
  /config/passenger:
    $ref: './paths/1.2.1.yaml#/config/passenger'
  /spawn/vehicle:
    $ref: './paths/1.2.2.yaml#/spawn/vehicle'
  /spawn/corridor:
    $ref: './paths/1.2.2.yaml#/spawn/corridor'
  /spawn/vpo:
    $ref: './paths/1.2.2.yaml#/spawn/vpo'
  /create/vertiport:
    $ref: './paths/1.2.3.yaml#/create/vertiport'
  /create/vehicle:
    $ref: './paths/1.2.3.yaml#/create/vehicle'
  /create/objects:
    $ref: './paths/1.2.4.yaml#/create/objects'
  /status/init-success:
    $ref: './paths/1.2.5.yaml#/status/init-success'
  /env/gust:
    $ref: './paths/1.3.1.yaml#/env/gust'
  /env/bird:
    $ref: './paths/1.3.1.yaml#/env/bird'
  /env/dynamic:
    $ref: './paths/1.3.2.yaml#/env/dynamic'

  # ==========================================
  # 2. Execution
  # ==========================================
  /socket/monitoring:
    $ref: './paths/2.0.1.yaml#/socket/monitoring'
  /socket/env:
    $ref: './paths/2.0.2.yaml#/socket/env'
  /socket/vehicle:
    $ref: './paths/2.0.3.yaml#/socket/vehicle'
  /socket/ue-sensor:
    $ref: './paths/2.0.4.yaml#/socket/ue-sensor'
  /socket/py-sensor:
    $ref: './paths/2.0.5.yaml#/socket/py-sensor'
  /sim/start:
    $ref: './paths/2.1.1.yaml#/sim/start'
  /fpl/generate:
    $ref: './paths/2.1.2.yaml#/fpl/generate'
  /fpl/set:
    $ref: './paths/2.1.3.yaml#/fpl/set'
  /state/desire:
    $ref: './paths/2.1.4.yaml#/state/desire'

  # ==========================================
  # 3. Event Propagation
  # ==========================================
  /event/socket/env:
    $ref: './paths/3.0.1.yaml#/event/socket/env'
  /event/socket/monitoring:
    $ref: './paths/3.0.2.yaml#/event/socket/monitoring'
  /event/socket/sensor:
    $ref: './paths/3.0.3.yaml#/event/socket/sensor'
  /event/dynamic-handle:
    $ref: './paths/3.1.1.yaml#/event/dynamic-handle'
  /status/vertiport:
    $ref: './paths/3.2.1.yaml#/status/vertiport'
  /plan/global:
    $ref: './paths/3.2.2.yaml#/plan/global'
  /state/current/desire:
    $ref: './paths/3.2.3.yaml#/state/current/desire'
  /plan/sa-replan:
    $ref: './paths/3.3.1.yaml#/plan/sa-replan'
  /plan/confirm:
    $ref: './paths/3.3.2.yaml#/plan/confirm'
  /event/desire-state:
    $ref: './paths/3.3.3.yaml#/event/desire-state'
